server:
  port: 8764

spring:
  application:
    name: springcloud-news-reg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinwen?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml




